import type { Client, ClientWithRelations, ClientListItem, ClientVisit, ClientNote, ClientConsent, ClientRelation } from '../types'

// =============================================================================
// ID Generator
// =============================================================================

function generateClientId(num: number): string {
  return `CLI-${String(num).padStart(7, '0')}`
}

// =============================================================================
// Mock Clients (15 clients with realistic French-Canadian data)
// =============================================================================

export const MOCK_CLIENTS: Client[] = [
  {
    clientId: generateClientId(1234567),
    firstName: 'Marie-Claire',
    lastName: 'Dubois',
    birthFirstName: null,
    pronouns: 'elle/elle',
    sex: 'female',
    language: 'fr',
    birthday: '1985-03-15',
    email: 'marie.dubois@gmail.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0101',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: '514-555-1001',
    workPhoneExtension: '234',
    streetNumber: '1234',
    streetName: 'Rue Saint-Denis',
    apartment: '4B',
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2X 3K5',
    lastAppointmentDateTime: '2026-01-15T14:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Dre Marie Tremblay',
    primaryProfessionalId: 'pro-1',
    referredBy: 'Médecin de famille',
    customField: null,
    tags: ['Entreprise MANA', 'Régulier'],
    createdAt: '2024-06-12T10:00:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234568),
    firstName: 'Jean-Philippe',
    lastName: 'Tremblay',
    birthFirstName: null,
    pronouns: 'il/lui',
    sex: 'male',
    language: 'fr',
    birthday: '1978-09-22',
    email: 'jp.tremblay@outlook.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0102',
    homePhoneCountryCode: '+1',
    homePhone: '514-555-2002',
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '567',
    streetName: 'Boulevard René-Lévesque',
    apartment: null,
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2Z 1A7',
    lastAppointmentDateTime: '2026-01-10T10:00:00.000Z',
    lastAppointmentService: 'Consultation couple',
    lastAppointmentProfessional: 'Jean-Philippe Bouchard',
    primaryProfessionalId: 'pro-2',
    referredBy: 'Bouche à oreille',
    customField: null,
    tags: ['Nouveau client'],
    createdAt: '2025-11-05T09:30:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234569),
    firstName: 'Sophie',
    lastName: 'Gagnon-Leclerc',
    birthFirstName: 'Sophie',
    pronouns: 'elle/elle',
    sex: 'female',
    language: 'fr',
    birthday: '1992-12-08',
    email: 'sophie.gl@gmail.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '438-555-0103',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '89',
    streetName: 'Avenue du Parc',
    apartment: '12',
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2V 4E6',
    lastAppointmentDateTime: '2026-01-18T16:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Sophie Gagnon',
    primaryProfessionalId: 'pro-3',
    referredBy: 'Programme d\'aide aux employés',
    customField: 'Préfère les rendez-vous en fin de journée',
    tags: ['PAE', 'Régulier'],
    createdAt: '2024-02-20T14:15:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234570),
    firstName: 'Martin',
    lastName: 'Côté',
    birthFirstName: null,
    pronouns: null,
    sex: 'male',
    language: 'fr',
    birthday: '1965-05-30',
    email: 'martin.cote@videotron.ca',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0104',
    homePhoneCountryCode: '+1',
    homePhone: '514-555-4004',
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '2345',
    streetName: 'Rue Sherbrooke Est',
    apartment: null,
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2K 1E8',
    lastAppointmentDateTime: '2025-12-20T11:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Dre Marie Tremblay',
    primaryProfessionalId: 'pro-1',
    referredBy: null,
    customField: null,
    tags: [],
    createdAt: '2023-08-10T08:00:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234571),
    firstName: 'Amélie',
    lastName: 'Bouchard',
    birthFirstName: null,
    pronouns: 'elle/elle',
    sex: 'female',
    language: 'fr',
    birthday: '1988-07-14',
    email: 'amelie.b@gmail.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0105',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '456',
    streetName: 'Avenue Laurier Ouest',
    apartment: '8',
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2V 2K5',
    lastAppointmentDateTime: null,
    lastAppointmentService: null,
    lastAppointmentProfessional: null,
    primaryProfessionalId: 'pro-1',
    referredBy: 'Site web',
    customField: null,
    tags: ['Nouveau client'],
    createdAt: '2026-01-08T11:45:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234572),
    firstName: 'François',
    lastName: 'Lavoie',
    birthFirstName: null,
    pronouns: 'il/lui',
    sex: 'male',
    language: 'fr',
    birthday: '1975-11-25',
    email: null,
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0106',
    homePhoneCountryCode: '+1',
    homePhone: '514-555-6006',
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '789',
    streetName: 'Rue de la Montagne',
    apartment: null,
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H3G 1Z2',
    lastAppointmentDateTime: '2025-06-15T09:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Jean-Philippe Bouchard',
    primaryProfessionalId: 'pro-2',
    referredBy: 'Référence médicale',
    customField: null,
    tags: [],
    createdAt: '2024-01-15T16:30:00.000Z',
    isArchived: true,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234573),
    firstName: 'Isabelle',
    lastName: 'Roy',
    birthFirstName: 'Isabelle',
    pronouns: 'elle/elle',
    sex: 'female',
    language: 'fr',
    birthday: '1990-02-28',
    email: 'isabelle.roy@hotmail.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '438-555-0107',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: '514-555-7007',
    workPhoneExtension: '101',
    streetNumber: '321',
    streetName: 'Rue Saint-Hubert',
    apartment: '5A',
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2R 2N1',
    lastAppointmentDateTime: '2026-01-17T15:30:00.000Z',
    lastAppointmentService: 'Évaluation neuropsychologique',
    lastAppointmentProfessional: 'Sophie Gagnon',
    primaryProfessionalId: 'pro-3',
    referredBy: 'Neurologue',
    customField: 'Évaluation en cours',
    tags: ['Neuropsychologie', 'Urgent'],
    createdAt: '2025-12-01T10:00:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234574),
    firstName: 'Alexandre',
    lastName: 'Morin',
    birthFirstName: null,
    pronouns: 'il/lui',
    sex: 'male',
    language: 'en',
    birthday: '1983-08-19',
    email: 'alex.morin@gmail.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0108',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '654',
    streetName: 'Rue Notre-Dame Ouest',
    apartment: null,
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H3C 1K3',
    lastAppointmentDateTime: '2026-01-12T13:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Dre Marie Tremblay',
    primaryProfessionalId: 'pro-1',
    referredBy: null,
    customField: null,
    tags: ['Anglophone'],
    createdAt: '2024-09-22T14:00:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234575),
    firstName: 'Émilie',
    lastName: 'Bergeron',
    birthFirstName: null,
    pronouns: 'elle/elle',
    sex: 'female',
    language: 'fr',
    birthday: '1995-04-10',
    email: 'emilie.bergeron@uqam.ca',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0109',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '987',
    streetName: 'Avenue du Mont-Royal Est',
    apartment: '3',
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2J 1W8',
    lastAppointmentDateTime: '2026-01-19T10:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Jean-Philippe Bouchard',
    primaryProfessionalId: 'pro-2',
    referredBy: 'Services aux étudiants UQAM',
    customField: null,
    tags: ['Étudiant', 'Régulier'],
    createdAt: '2025-09-01T08:30:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234576),
    firstName: 'Pierre-Luc',
    lastName: 'Pelletier',
    birthFirstName: null,
    pronouns: null,
    sex: 'male',
    language: 'fr',
    birthday: '1970-06-05',
    email: 'pl.pelletier@bell.net',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0110',
    homePhoneCountryCode: '+1',
    homePhone: '514-555-1010',
    workPhoneCountryCode: '+1',
    workPhone: '514-555-2010',
    workPhoneExtension: '500',
    streetNumber: '1111',
    streetName: 'Boulevard Saint-Laurent',
    apartment: null,
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2X 2S5',
    lastAppointmentDateTime: '2025-11-30T14:00:00.000Z',
    lastAppointmentService: 'Consultation couple',
    lastAppointmentProfessional: 'Dre Marie Tremblay',
    primaryProfessionalId: 'pro-1',
    referredBy: 'Ancien client',
    customField: null,
    tags: [],
    createdAt: '2023-05-15T09:00:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234577),
    firstName: 'Léa',
    lastName: 'Pelletier',
    birthFirstName: null,
    pronouns: 'elle/elle',
    sex: 'female',
    language: 'fr',
    birthday: '2012-09-15',
    email: null,
    cellPhoneCountryCode: '+1',
    cellPhone: null,
    homePhoneCountryCode: '+1',
    homePhone: '514-555-1010',
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '1111',
    streetName: 'Boulevard Saint-Laurent',
    apartment: null,
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2X 2S5',
    lastAppointmentDateTime: '2026-01-16T16:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Sophie Gagnon',
    primaryProfessionalId: 'pro-3',
    referredBy: 'Référence parentale',
    customField: 'Mineure - consentement parental requis',
    tags: ['Mineur'],
    createdAt: '2025-10-20T11:00:00.000Z',
    isArchived: false,
    responsibleClientId: generateClientId(1234576), // Pierre-Luc Pelletier (father)
  },
  {
    clientId: generateClientId(1234578),
    firstName: 'Caroline',
    lastName: 'Lefebvre',
    birthFirstName: 'Caroline',
    pronouns: 'elle/elle',
    sex: 'female',
    language: 'fr',
    birthday: '1982-01-20',
    email: 'caroline.lefebvre@gmail.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '438-555-0112',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '222',
    streetName: 'Rue Beaubien Est',
    apartment: '6',
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2S 1R8',
    lastAppointmentDateTime: '2024-08-10T09:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Dre Marie Tremblay',
    primaryProfessionalId: 'pro-1',
    referredBy: null,
    customField: null,
    tags: [],
    createdAt: '2022-03-05T10:00:00.000Z',
    isArchived: true,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234579),
    firstName: 'Nicolas',
    lastName: 'Simard',
    birthFirstName: null,
    pronouns: 'il/lui',
    sex: 'male',
    language: 'fr',
    birthday: '1998-10-30',
    email: 'nicolas.simard@outlook.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0113',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '333',
    streetName: 'Avenue Papineau',
    apartment: '2B',
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2K 4J5',
    lastAppointmentDateTime: '2026-01-14T11:00:00.000Z',
    lastAppointmentService: 'Appel découverte',
    lastAppointmentProfessional: 'Jean-Philippe Bouchard',
    primaryProfessionalId: 'pro-2',
    referredBy: 'Google',
    customField: null,
    tags: ['Nouveau client'],
    createdAt: '2026-01-10T15:00:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234580),
    firstName: 'Nathalie',
    lastName: 'Ouellet',
    birthFirstName: null,
    pronouns: 'elle/elle',
    sex: 'female',
    language: 'fr',
    birthday: '1979-12-12',
    email: 'n.ouellet@yahoo.ca',
    cellPhoneCountryCode: '+1',
    cellPhone: '514-555-0114',
    homePhoneCountryCode: '+1',
    homePhone: '514-555-1414',
    workPhoneCountryCode: '+1',
    workPhone: null,
    workPhoneExtension: null,
    streetNumber: '444',
    streetName: 'Rue Rachel Est',
    apartment: null,
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2J 2H6',
    lastAppointmentDateTime: '2026-01-13T15:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Dre Marie Tremblay',
    primaryProfessionalId: 'pro-1',
    referredBy: 'Médecin de famille',
    customField: null,
    tags: ['Régulier'],
    createdAt: '2024-04-18T13:30:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
  {
    clientId: generateClientId(1234581),
    firstName: 'Marc-André',
    lastName: 'Fortin',
    birthFirstName: null,
    pronouns: 'il/lui',
    sex: 'male',
    language: 'fr',
    birthday: '1987-03-25',
    email: 'ma.fortin@gmail.com',
    cellPhoneCountryCode: '+1',
    cellPhone: '438-555-0115',
    homePhoneCountryCode: '+1',
    homePhone: null,
    workPhoneCountryCode: '+1',
    workPhone: '514-555-1515',
    workPhoneExtension: '300',
    streetNumber: '555',
    streetName: 'Rue Saint-Catherine Est',
    apartment: '10C',
    city: 'Montréal',
    province: 'QC',
    country: 'Canada',
    postalCode: 'H2L 2E2',
    lastAppointmentDateTime: '2026-01-11T10:00:00.000Z',
    lastAppointmentService: 'Consultation individuelle',
    lastAppointmentProfessional: 'Sophie Gagnon',
    primaryProfessionalId: 'pro-3',
    referredBy: 'PAE Desjardins',
    customField: null,
    tags: ['PAE', 'Régulier'],
    createdAt: '2025-06-10T09:00:00.000Z',
    isArchived: false,
    responsibleClientId: null,
  },
]

// =============================================================================
// Mock Visits
// =============================================================================

export const MOCK_VISITS: Record<string, ClientVisit[]> = {
  [generateClientId(1234567)]: [
    { id: 'v-1', date: '2026-01-15T14:00:00.000Z', serviceName: 'Consultation individuelle', professionalName: 'Dre Marie Tremblay', status: 'completed', amount: 150 },
    { id: 'v-2', date: '2026-01-08T14:00:00.000Z', serviceName: 'Consultation individuelle', professionalName: 'Dre Marie Tremblay', status: 'completed', amount: 150 },
    { id: 'v-3', date: '2025-12-18T14:00:00.000Z', serviceName: 'Consultation individuelle', professionalName: 'Dre Marie Tremblay', status: 'completed', amount: 150 },
    { id: 'v-4', date: '2025-12-04T14:00:00.000Z', serviceName: 'Consultation individuelle', professionalName: 'Dre Marie Tremblay', status: 'cancelled', amount: 0 },
  ],
  [generateClientId(1234568)]: [
    { id: 'v-5', date: '2026-01-10T10:00:00.000Z', serviceName: 'Consultation couple', professionalName: 'Jean-Philippe Bouchard', status: 'completed', amount: 180 },
  ],
}

// =============================================================================
// Mock Notes
// =============================================================================

export const MOCK_NOTES: Record<string, ClientNote[]> = {
  [generateClientId(1234567)]: [
    { id: 'n-1', content: 'Cliente montre des progrès significatifs dans la gestion de l\'anxiété.', createdAt: '2026-01-15T15:00:00.000Z', authorName: 'Dre Marie Tremblay' },
    { id: 'n-2', content: 'À revoir les objectifs thérapeutiques lors de la prochaine séance.', createdAt: '2026-01-08T15:00:00.000Z', authorName: 'Dre Marie Tremblay' },
  ],
  [generateClientId(1234573)]: [
    { id: 'n-3', content: 'Début du processus d\'évaluation neuropsychologique. Tests prévus sur 3 séances.', createdAt: '2026-01-17T17:00:00.000Z', authorName: 'Sophie Gagnon' },
  ],
}

// =============================================================================
// Mock Consents
// =============================================================================

export const MOCK_CONSENTS: Record<string, ClientConsent[]> = {
  [generateClientId(1234567)]: [
    { id: 'c-1', type: 'Consentement aux soins', status: 'valid', signedAt: '2024-06-12T10:00:00.000Z', expiresAt: '2026-06-12T10:00:00.000Z', signedBy: 'Marie-Claire Dubois' },
    { id: 'c-2', type: 'Autorisation de communication', status: 'valid', signedAt: '2024-06-12T10:00:00.000Z', expiresAt: null, signedBy: 'Marie-Claire Dubois' },
  ],
  [generateClientId(1234568)]: [
    { id: 'c-3', type: 'Consentement aux soins', status: 'valid', signedAt: '2025-11-05T09:30:00.000Z', expiresAt: '2027-11-05T09:30:00.000Z', signedBy: 'Jean-Philippe Tremblay' },
  ],
  [generateClientId(1234577)]: [
    { id: 'c-4', type: 'Consentement parental', status: 'valid', signedAt: '2025-10-20T11:00:00.000Z', expiresAt: '2026-10-20T11:00:00.000Z', signedBy: 'Pierre-Luc Pelletier' },
  ],
  [generateClientId(1234571)]: [
    { id: 'c-5', type: 'Consentement aux soins', status: 'missing', signedAt: null, expiresAt: null, signedBy: null },
  ],
}

// =============================================================================
// Mock Relations
// =============================================================================

export const MOCK_RELATIONS: Record<string, ClientRelation[]> = {
  [generateClientId(1234567)]: [
    { id: 'rel-1', relatedClientId: generateClientId(1234568), relatedClientName: 'Jean-Philippe Tremblay', relationType: 'spouse' },
  ],
  [generateClientId(1234568)]: [
    { id: 'rel-2', relatedClientId: generateClientId(1234567), relatedClientName: 'Marie-Claire Dubois', relationType: 'spouse' },
  ],
  [generateClientId(1234576)]: [
    { id: 'rel-3', relatedClientId: generateClientId(1234577), relatedClientName: 'Émile Pelletier', relationType: 'child', notes: 'Fils' },
  ],
  [generateClientId(1234577)]: [
    { id: 'rel-4', relatedClientId: generateClientId(1234576), relatedClientName: 'Pierre-Luc Pelletier', relationType: 'parent', notes: 'Père' },
  ],
}

// =============================================================================
// Mock Professionals (for filtering)
// =============================================================================

export const MOCK_PROFESSIONALS = [
  { id: 'pro-1', displayName: 'Dre Marie Tremblay' },
  { id: 'pro-2', displayName: 'Jean-Philippe Bouchard' },
  { id: 'pro-3', displayName: 'Sophie Gagnon' },
]

const professionalMap: Record<string, string> = {
  'pro-1': 'Dre Marie Tremblay',
  'pro-2': 'Jean-Philippe Bouchard',
  'pro-3': 'Sophie Gagnon',
}

// =============================================================================
// Transform to List Items
// =============================================================================

export function clientToListItem(client: Client): ClientListItem {
  return {
    id: client.clientId,
    clientId: client.clientId,
    firstName: client.firstName,
    lastName: client.lastName,
    birthday: client.birthday,
    email: client.email,
    cellPhone: client.cellPhone,
    lastAppointmentDateTime: client.lastAppointmentDateTime,
    status: client.isArchived ? 'archived' : 'active',
    tags: client.tags,
    primaryProfessionalId: client.primaryProfessionalId,
    primaryProfessionalName: client.primaryProfessionalId
      ? professionalMap[client.primaryProfessionalId] || null
      : null,
  }
}

export const MOCK_CLIENT_LIST_ITEMS: ClientListItem[] = MOCK_CLIENTS.map(clientToListItem)

// =============================================================================
// Get Client with Relations (for drawer)
// =============================================================================

export function getClientWithRelations(clientId: string): ClientWithRelations | undefined {
  const client = MOCK_CLIENTS.find(c => c.clientId === clientId)
  if (!client) return undefined

  const visits = MOCK_VISITS[clientId] || []
  const notes = MOCK_NOTES[clientId] || []
  const consents = MOCK_CONSENTS[clientId] || []
  const relations = MOCK_RELATIONS[clientId] || []

  // Mock balance (assume fully paid)
  const balance = 0

  // Get responsible client info if exists
  let responsibleClient = null
  if (client.responsibleClientId) {
    const responsible = MOCK_CLIENTS.find(c => c.clientId === client.responsibleClientId)
    if (responsible) {
      responsibleClient = {
        clientId: responsible.clientId,
        firstName: responsible.firstName,
        lastName: responsible.lastName,
      }
    }
  }

  // Mock primary professional info
  const professionalMap: Record<string, { id: string; displayName: string }> = {
    'pro-1': { id: 'pro-1', displayName: 'Dre Marie Tremblay' },
    'pro-2': { id: 'pro-2', displayName: 'Jean-Philippe Bouchard' },
    'pro-3': { id: 'pro-3', displayName: 'Sophie Gagnon' },
  }
  const primaryProfessional = client.primaryProfessionalId
    ? professionalMap[client.primaryProfessionalId] || null
    : null

  return {
    ...client,
    visits,
    notes,
    consents,
    relations,
    balance,
    responsibleClient,
    primaryProfessional,
  }
}

// =============================================================================
// Available Tags (for filtering)
// =============================================================================

export const AVAILABLE_TAGS = [
  'Entreprise MANA',
  'Régulier',
  'Nouveau client',
  'PAE',
  'Neuropsychologie',
  'Urgent',
  'Anglophone',
  'Étudiant',
  'Mineur',
]
