export { InfoSection } from './info-section'
export { ExternalPayersSection } from './external-payers-section'
export { VisitsSection } from './visits-section'
export { NotesSection } from './notes-section'
export { ConsentsSection } from './consents-section'
export { HistorySection } from './history-section'
export { RelationsSection } from './relations-section'
export * from './edit-dialogs'
export * from './external-payer-dialogs'
