// src/services-catalog/constants/mock-services.ts

import type { Service, PricingModel } from '../types'

// Mock services matching the v2 database schema
// NOTE: This is for development/testing only. Production uses real database data.
export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-001',
    key: 'ouverture_de_dossier',
    name: 'Ouverture de dossier',
    description: 'Frais administratifs pour l\'ouverture d\'un nouveau dossier client.',
    pricingModel: 'fixed' as PricingModel,
    duration: undefined,
    displayOrder: 1,
    colorHex: undefined,
    isActive: true,
    requiresConsent: true,
    isTaxableOverride: true,  // Administrative fee - always taxable
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-002',
    key: 'appel_decouverte',
    name: 'Appel découverte',
    description: 'Appel gratuit de 15 minutes pour évaluer les besoins du client.',
    pricingModel: 'fixed' as PricingModel,
    duration: 15,
    displayOrder: 2,
    colorHex: '#B8D4E3',
    isActive: true,
    requiresConsent: false,
    isTaxableOverride: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-003',
    key: 'consultation_individuelle',
    name: 'Consultation individuelle',
    description: 'Séance de suivi individuel avec un professionnel.',
    pricingModel: 'by_profession_category' as PricingModel,
    duration: 50,
    displayOrder: 3,
    colorHex: '#7FAE9D',
    isActive: true,
    requiresConsent: false,
    isTaxableOverride: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-004',
    key: 'consultation_couple',
    name: 'Consultation de couple',
    description: 'Séance de suivi pour couples.',
    pricingModel: 'by_profession_category' as PricingModel,
    duration: 60,
    displayOrder: 4,
    colorHex: '#B8D4E3',
    isActive: true,
    requiresConsent: false,
    isTaxableOverride: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-005',
    key: 'seance_prolongee',
    name: 'Séance prolongée',
    description: 'Séance de 90 minutes pour situations complexes.',
    pricingModel: 'by_profession_category' as PricingModel,
    duration: 90,
    displayOrder: 5,
    colorHex: '#E8D5B7',
    isActive: true,
    requiresConsent: false,
    isTaxableOverride: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-006',
    key: 'frais_annulation',
    name: 'Frais d\'annulation',
    description: 'Frais appliqués en cas d\'annulation moins de 24 heures avant le rendez-vous.',
    pricingModel: 'rule_cancellation_prorata' as PricingModel,
    duration: undefined,
    displayOrder: 10,
    colorHex: undefined,
    isActive: true,
    requiresConsent: false,
    isTaxableOverride: true,  // Administrative fee - always taxable
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-007',
    key: 'discussion_autre_intervenant',
    name: 'Discussion avec un autre intervenant',
    description: 'Temps de discussion ou coordination avec un autre professionnel.',
    pricingModel: 'by_profession_hourly_prorata' as PricingModel,
    duration: undefined,
    displayOrder: 11,
    colorHex: undefined,
    isActive: true,
    requiresConsent: false,
    isTaxableOverride: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-008',
    key: 'redaction_de_rapport',
    name: 'Rédaction de rapport',
    description: 'Temps de rédaction de rapports, notes cliniques détaillées ou documents officiels.',
    pricingModel: 'by_profession_hourly_prorata' as PricingModel,
    duration: undefined,
    displayOrder: 12,
    colorHex: undefined,
    isActive: true,
    requiresConsent: false,
    isTaxableOverride: null,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
]

// Internal type display labels (i18n keys) - DEPRECATED, kept for backwards compatibility
export const INTERNAL_TYPE_LABELS: Record<string, string> = {
  ouverture_dossier: 'pages.services.internalTypes.ouvertureDossier',
  consultation: 'pages.services.internalTypes.consultation',
  appel_decouverte: 'pages.services.internalTypes.appelDecouverte',
  annulation_frais: 'pages.services.internalTypes.annulationFrais',
  autre: 'pages.services.internalTypes.autre',
}
