// src/services-catalog/constants/mock-services.ts

import type { Service } from '../types'

// Mock services matching GoRendezVous list but with variants instead of duplicates
export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-001',
    name: 'Ouverture de dossier',
    description: 'Première rencontre pour ouvrir un dossier client.',
    duration: 60,
    price: 43.49,
    isOnlineAvailable: true,
    internalType: 'ouverture_dossier',
    variants: [
      { id: 'var-001-1', label: 'Individuel' },
      { id: 'var-001-2', label: 'Couple' },
      { id: 'var-001-3', label: 'Médiation' },
      { id: 'var-001-4', label: 'Service de consultation' },
    ],
    isActive: true,
    displayOrder: 1,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-002',
    name: 'Consultation individuelle',
    description: 'Séance de suivi individuel avec un professionnel.',
    duration: 50,
    price: 130,
    isOnlineAvailable: true,
    internalType: 'consultation',
    variants: [],
    isActive: true,
    displayOrder: 2,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-003',
    name: 'Consultation de couple',
    description: 'Séance de suivi pour couples.',
    duration: 60,
    price: 150,
    isOnlineAvailable: true,
    internalType: 'consultation',
    variants: [],
    isActive: true,
    displayOrder: 3,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-004',
    name: 'Appel découverte',
    description: 'Appel gratuit de 15 minutes pour évaluer les besoins.',
    duration: 15,
    price: 0,
    isOnlineAvailable: true,
    internalType: 'appel_decouverte',
    variants: [],
    isActive: true,
    displayOrder: 4,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-005',
    name: 'Séance prolongée',
    description: 'Séance de 90 minutes pour situations complexes.',
    duration: 90,
    price: 195,
    isOnlineAvailable: false,
    internalType: 'consultation',
    variants: [],
    isActive: true,
    displayOrder: 5,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-006',
    name: 'Frais d\'annulation',
    description: 'Frais appliqués pour annulation tardive (< 24h).',
    duration: 0,
    price: 80,
    isOnlineAvailable: false,
    internalType: 'annulation_frais',
    variants: [],
    isActive: true,
    displayOrder: 6,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'srv-007',
    name: 'Consultation famille',
    description: 'Séance de thérapie familiale.',
    duration: 75,
    price: 170,
    isOnlineAvailable: false,
    internalType: 'consultation',
    variants: [],
    isActive: false,  // Archived example
    displayOrder: 7,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
]

// Internal type display labels (i18n keys)
export const INTERNAL_TYPE_LABELS: Record<string, string> = {
  ouverture_dossier: 'pages.services.internalTypes.ouvertureDossier',
  consultation: 'pages.services.internalTypes.consultation',
  appel_decouverte: 'pages.services.internalTypes.appelDecouverte',
  annulation_frais: 'pages.services.internalTypes.annulationFrais',
  autre: 'pages.services.internalTypes.autre',
}
