function Professionnels({ role, selected, setSelected }) {
  const { Card, Badge, Avatar, Button, Icon, Input, Select, PageHeader, Dialog, Label, Checkbox, Toast } = DS;
  const [q, setQ] = React.useState(''); const [status, setStatus] = React.useState('all'); const [add, setAdd] = React.useState(false); const [toast, setToast] = React.useState(null);
  const list = PROS.filter(p => (status === 'all' || p.status === status) && (!q || (p.name + p.email).toLowerCase().includes(q.toLowerCase())));
  if (selected) return <Fiche pro={selected} role={role} back={() => setSelected(null)} />;
  const cols = 'minmax(0,2fr) minmax(0,1.6fr) 96px 72px minmax(0,1.4fr)';
  return <>
    <PageHeader title="Professionnels" subtitle={PROS.length + ' professionnels · ' + PROS.filter(p => p.status === 'active').length + ' actifs'} actions={<Button onClick={() => setAdd(true)}><Icon name="plus" size={14} /> Ajouter</Button>} />
    <div className="kit-row" style={{ gap: 8 }}><Input icon="search" placeholder="Rechercher par nom ou courriel…" value={q} onChange={e => setQ(e.target.value)} wrapStyle={{ maxWidth: 280 }} /><Select value={status} onChange={e => setStatus(e.target.value)} style={{ width: 160 }} options={[{ value: 'all', label: 'Tous les statuts' }, { value: 'active', label: 'Actif' }, { value: 'invited', label: 'Invité' }, { value: 'pending', label: 'En attente' }, { value: 'inactive', label: 'Inactif' }]} /><Button variant="ghost"><Icon name="filter" size={14} /> Filtres</Button><span style={{ flex: 1 }} /><span className="kit-muted kit-nowrap" style={{ font: 'var(--type-caption)' }}>{list.length} résultat{list.length > 1 ? 's' : ''}</span></div>
    <Card padding={0}><Head cols={cols}><span>Nom</span><span>Profession</span><span>Statut</span><span>Documents</span><span>À surveiller</span></Head>
      {list.map(p => <Row key={p.id} cols={cols} onClick={() => setSelected(p)} style={{ borderTop: '1px solid var(--border)' }}>
        <span className="kit-row" style={{ gap: 10, minWidth: 0 }}><Avatar name={p.name} size="sm" /><span style={{ minWidth: 0 }}><p style={{ margin: 0, font: 'var(--type-label)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{p.name}</p><p style={{ margin: 0, font: 'var(--type-caption)', color: 'var(--text-muted)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{p.email}</p></span></span>
        <span style={{ minWidth: 0 }}><p style={{ margin: 0, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{p.profession}</p><p style={{ margin: 0, font: 'var(--type-caption)', color: 'var(--text-muted)' }}>{p.order} {p.licence}</p></span>
        <span><Badge variant={STATUS[p.status][0]}>{STATUS[p.status][1]}</Badge></span>
        <span className="kit-num kit-muted">{p.docs} / 3</span>
        <span style={{ font: 'var(--type-caption)', color: p.expiring ? 'var(--danger)' : 'var(--text-muted)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{p.expiring ? 'Assurance expire ' + p.expiry.replace(' 2026', '') : p.pendingInvite ? 'Invitation sans réponse · 6 j' : p.status === 'pending' ? 'Dossier à réviser' : '—'}</span>
      </Row>)}
      <div className="kit-tfoot"><span>{list.length} sur {PROS.length} professionnels</span><span className="kit-row" style={{ gap: 4 }}><Button variant="ghost" size="sm" disabled><Icon name="chevron-left" size={14} /></Button><span>Page 1 sur 1</span><Button variant="ghost" size="sm" disabled><Icon name="chevron-right" size={14} /></Button></span></div>
    </Card>
    {list.length === 0 && <DS.EmptyState title="Aucun professionnel ne correspond" description="Modifiez la recherche ou les filtres." action={<Button variant="outline" size="sm" onClick={() => { setQ(''); setStatus('all'); }}>Réinitialiser</Button>} />}
    {add && <Dialog open onClose={() => setAdd(false)} title="Ajouter un professionnel" description="Une invitation lui sera envoyée par courriel pour compléter son profil." footer={<><Button variant="outline" onClick={() => setAdd(false)}>Annuler</Button><Button onClick={() => { setAdd(false); setToast('Invitation envoyée.'); setTimeout(() => setToast(null), 3000); }}>Créer et inviter</Button></>}>
      <div className="kit-col" style={{ gap: 12 }}><div className="kit-col"><Label required>Nom complet</Label><Input placeholder="Prénom Nom" autoFocus /></div><div className="kit-col"><Label required>Courriel</Label><Input type="email" placeholder="prenom@exemple.com" /></div><div className="kit-col"><Label>Profession</Label><Select placeholder="Choisir une profession" options={['Psychologue', 'Psychothérapeute', 'Travailleur social', 'Sexologue', 'Psychoéducateur', 'Nutritionniste', "Conseiller d'orientation"]} /></div><Checkbox label="Envoyer l'invitation maintenant" defaultChecked /></div>
    </Dialog>}
    {toast && <div style={{ position: 'fixed', right: 20, bottom: 20, zIndex: 60 }}><Toast variant="success" title={toast} onDismiss={() => setToast(null)} /></div>}
  </>;
}
function Fiche({ pro, role, back }) {
  const { Card, Badge, Avatar, Button, Icon, NavTabs, PageHeader, StatusIndicator, DropdownMenu, Input, Label, Select } = DS;
  const tabs = [{ id: 'apercu', label: 'Aperçu' }, { id: 'profil', label: 'Profil' }, { id: 'public', label: 'Profil public' }, { id: 'documents', label: 'Documents', count: pro.docs }, { id: 'contrats', label: 'Contrats' }];
  if (role === 'admin') tabs.push({ id: 'remu', label: 'Rémunération et fiscalité' });
  tabs.push({ id: 'courriels', label: 'Courriels' }, { id: 'historique', label: 'Historique' });
  const [tab, setTab] = React.useState('apercu');
  const docs = [{ n: 'Assurance responsabilité professionnelle', e: pro.expiry || '—', s: pro.expiring ? 'warning' : pro.status === 'active' ? 'complete' : 'pending' }, { n: 'Permis ' + pro.order, e: '31 mars 2027', s: pro.docs >= 2 ? 'complete' : 'pending' }, { n: 'Contrat de services', e: 'Signé le 12 janv. 2026', s: pro.docs >= 3 ? 'complete' : 'pending' }];
  const Kv = ({ k, v }) => <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, padding: '6px 0', borderBottom: '1px solid var(--border)', font: 'var(--type-body)' }}><span style={{ color: 'var(--text-secondary)' }}>{k}</span><span className="kit-num" style={{ fontWeight: 500, whiteSpace: 'nowrap' }}>{v}</span></div>;
  return <>
    <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><Avatar name={pro.name} size="lg" /><div style={{ flex: 1, minWidth: 0 }}><div className="kit-row"><h2 style={{ margin: 0, font: 'var(--type-page-title)', letterSpacing: 'var(--tracking-tight)' }}>{pro.name}</h2><Badge variant={STATUS[pro.status][0]}>{STATUS[pro.status][1]}</Badge></div><p style={{ margin: '2px 0 0', font: 'var(--type-body)', color: 'var(--text-secondary)' }}>{pro.profession} · {pro.order} {pro.licence} · {pro.email}</p></div><div className="kit-row" style={{ gap: 6 }}><DropdownMenu trigger={<Button variant="outline" size="icon" aria-label="Actions"><Icon name="ellipsis" size={14} /></Button>} items={[{ label: 'Modifier le profil', icon: 'pencil' }, { label: 'Renvoyer l\'invitation', icon: 'send' }, '-', { label: pro.status === 'inactive' ? 'Réactiver' : 'Désactiver', icon: 'user-x', tone: pro.status === 'inactive' ? undefined : 'danger' }]} /><Button variant="outline"><Icon name="file-text" size={14} /> Fiche PDF</Button><Button><Icon name="send" size={14} /> Envoyer au client</Button></div></div>
    <NavTabs tabs={tabs} value={tab} onChange={setTab} />
    {tab === 'apercu' && <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,2fr) minmax(240px,1fr)', gap: 20 }}>
      <Card title="Liste de vérification" description="Invitation → questionnaire → documents → révision → contrat → activation"><div><StatusIndicator status="complete" label="Invitation acceptée" description="12 déc. 2025" /><StatusIndicator status="complete" label="Questionnaire complété" description="professions, ordre, permis, spécialités" /><StatusIndicator status={docs[0].s} label={docs[0].n} description={pro.expiring ? 'expire le ' + pro.expiry + ' · renouvellement demandé' : 'valide jusqu\'au ' + docs[0].e} /><StatusIndicator status={docs[2].s} label="Contrat signé (Documenso)" description={docs[2].e} /><StatusIndicator status={pro.status === 'active' ? 'complete' : 'pending'} label="Profil activé" description={pro.status === 'active' ? 'visible dans les suggestions de jumelage' : 'en attente de révision'} style={{ borderBottom: 0 }} /></div></Card>
      <div className="kit-col" style={{ gap: 20 }}><Card title="Prochaine action">{pro.expiring ? <><p style={{ margin: 0, font: 'var(--type-body)', color: 'var(--text-secondary)' }}>Relancer pour la preuve d'assurance renouvelée avant le {pro.expiry}.</p><Button style={{ marginTop: 12 }} size="sm"><Icon name="mail" size={14} /> Envoyer un rappel</Button></> : <p style={{ margin: 0, font: 'var(--type-body)', color: 'var(--text-secondary)' }}>Rien à faire. Le dossier est complet.</p>}</Card><Card title="Tarifs" description="Fiche d'honoraires · annexe A"><div><Kv k="Individuel · 50 min" v={pro.rate + ',00 $'} /><Kv k="Couple / famille · 60 min" v={(pro.rate + 20) + ',00 $'} /><Kv k="Marge clinique" v="28 %" /></div></Card></div>
    </div>}
    {tab === 'documents' && <Card padding={0}><Head cols="2fr 1fr 1fr 32px"><span>Document</span><span>Expiration</span><span>Statut</span><span /></Head>{docs.map(d => <Row key={d.n} cols="2fr 1fr 1fr 32px" style={{ borderTop: '1px solid var(--border)' }}><span className="kit-row"><Icon name="file-text" size={14} style={{ color: 'var(--text-muted)' }} />{d.n}</span><span className="kit-num">{d.e}</span><span><Badge variant={d.s === 'complete' ? 'success' : d.s === 'warning' ? 'error' : 'outline'}>{d.s === 'complete' ? 'Valide' : d.s === 'warning' ? 'Expire bientôt' : 'Manquant'}</Badge></span><Button variant="ghost" size="icon-sm" aria-label="Télécharger"><Icon name="download" size={14} /></Button></Row>)}<div style={{ padding: 12, borderTop: '1px solid var(--border)' }}><Button variant="outline" size="sm"><Icon name="upload" size={14} /> Téléverser un document</Button></div></Card>}
    {tab === 'profil' && <Card title="Identité et profession" style={{ maxWidth: 'var(--form-max)' }}><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}><div className="kit-col"><Label>Prénom</Label><Input defaultValue={pro.name.split(' ')[0]} /></div><div className="kit-col"><Label>Nom</Label><Input defaultValue={pro.name.split(' ').slice(1).join(' ')} /></div><div className="kit-col"><Label>Profession</Label><Select defaultValue={pro.profession} options={['Psychologue', 'Psychothérapeute', 'Travailleur social', 'Sexologue', 'Psychoéducateur', 'Nutritionniste']} /></div><div className="kit-col"><Label>Ordre professionnel</Label><Input defaultValue={pro.order} /></div><div className="kit-col"><Label>N° de permis</Label><Input defaultValue={pro.licence} /></div><div className="kit-col"><Label>Courriel</Label><Input defaultValue={pro.email} /></div></div><div className="kit-row" style={{ marginTop: 16, justifyContent: 'flex-end', gap: 6 }}><Button variant="outline">Annuler</Button><Button>Enregistrer</Button></div></Card>}
    {!['apercu', 'documents', 'profil'].includes(tab) && <DS.FullPageMessage compact title={tabs.find(t => t.id === tab).label} body="Cette section sera disponible avec le module Professionnels (phase 4)." />}
  </>;
}
Object.assign(window, { Professionnels, Fiche });
