function Demandes() {
  const { Card, Badge, Avatar, Button, Icon, Input, Select, PageHeader, Label, Textarea, Checkbox } = DS;
  const [open, setOpen] = React.useState(DEMANDES[0]); const [filter, setFilter] = React.useState('all');
  const list = DEMANDES.filter(d => filter === 'all' || d.status === filter);
  const tone = s => s === 'À rappeler' ? 'warning' : s === 'Jumelage proposé' ? 'success' : 'info';
  const cols = '72px minmax(0,2fr) minmax(0,1.3fr) minmax(150px,1.3fr) 48px';
  return <>
    <PageHeader title="Demandes" subtitle="Promesse de rappel en 24–48 h ouvrables" actions={<Button><Icon name="plus" size={14} /> Nouvelle demande</Button>} />
    <div className="kit-row" style={{ gap: 8 }}><Input icon="search" placeholder="Rechercher un client ou un numéro…" wrapStyle={{ maxWidth: 280 }} /><Select value={filter} onChange={e => setFilter(e.target.value)} style={{ width: 200 }} options={[{ value: 'all', label: 'Toutes les étapes' }, { value: 'À rappeler', label: 'À rappeler' }, { value: 'Appel découverte fait', label: 'Appel découverte fait' }, { value: 'Jumelage proposé', label: 'Jumelage proposé' }]} /></div>
    <div className="kit-split"><Card padding={0}><Head cols={cols}><span>N°</span><span>Client</span><span>Motifs</span><span>Étape</span><span style={{ textAlign: 'right' }}>Âge</span></Head>
      {list.map(d => <Row key={d.id} cols={cols} onClick={() => setOpen(d)} className={open && open.id === d.id ? 'is-selected' : ''} style={{ borderTop: '1px solid var(--border)' }}><span className="kit-num kit-muted" style={{ font: 'var(--type-caption)' }}>{d.id}</span><span className="kit-row" style={{ gap: 8, minWidth: 0 }}><Avatar name={d.client} size="sm" tone="neutral" /><span style={{ font: 'var(--type-label)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{d.client}</span>{d.urgency === 'haute' && <Badge variant="error" filled>Urgent</Badge>}</span><span style={{ color: 'var(--text-secondary)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{d.motifs.join(' · ')}</span><span style={{ minWidth: 0 }}><Badge variant={tone(d.status)} style={{ maxWidth: '100%', overflow: 'hidden', textOverflow: 'ellipsis' }}>{d.status}</Badge></span><span className="kit-num kit-muted" style={{ textAlign: 'right' }}>{d.age}</span></Row>)}
      <div className="kit-tfoot"><span>{list.length} demandes</span><span>Page 1 sur 1</span></div>
    </Card>
    {open ? <aside className="kit-panel" aria-label="Détail de la demande">
      <div className="kit-panel-h"><div style={{ minWidth: 0 }}><div className="kit-row" style={{ gap: 8 }}><h3 style={{ margin: 0, font: 'var(--type-section-title)' }}>{open.client}</h3>{open.urgency === 'haute' && <Badge variant="error" filled>Urgent</Badge>}</div><p className="kit-ellip" style={{ margin: '2px 0 0', font: 'var(--type-caption)', color: 'var(--text-muted)' }}>{open.id} · reçue il y a {open.age} · {open.source}</p></div><Button variant="ghost" size="icon-sm" aria-label="Fermer" onClick={() => setOpen(null)}><Icon name="x" size={14} /></Button></div>
      <div className="kit-panel-b">
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px 12px', font: 'var(--type-body)' }}>{[['Téléphone', open.phone], ['Disponibilités', open.pref], ['Payeur externe', open.payer || 'Aucun'], ['Urgence', open.urgency === 'haute' ? 'Haute' : 'Normale']].map(([k, v]) => <div key={k}><p className="kit-muted" style={{ margin: 0, font: 'var(--type-caption)' }}>{k}</p><p style={{ margin: 0 }}>{v}</p></div>)}</div>
        <div><h4 className="kit-h4">Appel découverte</h4><div className="kit-col" style={{ gap: 10 }}><div className="kit-col"><Label>Motifs <span className="kit-muted" style={{ fontWeight: 400 }}>(orientation, pas un diagnostic)</span></Label><div className="kit-row" style={{ gap: 6, flexWrap: 'wrap' }}>{open.motifs.map(m => <Badge key={m} dot={false}>{m}</Badge>)}<Button variant="ghost" size="sm"><Icon name="plus" size={12} /> Ajouter</Button></div></div><div className="kit-col"><Label>Besoin exprimé</Label><Textarea placeholder="En quelques mots, ce que la personne souhaite travailler…" style={{ minHeight: 72 }} /></div><div className="kit-col"><Label>Préférences</Label><div className="kit-row" style={{ gap: 14, flexWrap: 'wrap' }}><Checkbox label="Femme" /><Checkbox label="Homme" /><Checkbox label="Anglais" /><Checkbox label="Soirs" defaultChecked={open.pref.includes('Soirs')} /></div></div></div></div>
        <div><h4 className="kit-h4">Suggestions de professionnels</h4><p className="kit-muted" style={{ margin: '0 0 8px', font: 'var(--type-caption)' }}>Vous décidez ; l'app vous aide. Classées par spécialité et disponibilité.</p><Card padding={0} variant="outline">{PROS.filter(p => p.status === 'active').slice(0, 3).map((p, i) => <Row key={p.id} cols="24px 1fr auto auto" style={{ borderTop: i ? '1px solid var(--border)' : 0 }}><Avatar name={p.name} size="sm" /><div style={{ minWidth: 0 }}><p style={{ margin: 0, font: 'var(--type-label)' }}>{p.name}</p><p style={{ margin: 0, font: 'var(--type-caption)', color: 'var(--text-muted)' }}>{p.profession} · {p.rate},00 $ · dispo. jeudi 18 h</p></div>{i === 0 ? <Badge variant="success">Spécialisé</Badge> : <span />}<Button variant={i === 0 ? 'default' : 'outline'} size="sm">Choisir</Button></Row>)}</Card></div>
      </div>
      <div className="kit-panel-f"><Button variant="outline" size="sm"><Icon name="phone" size={14} /> Noter l'appel</Button><Button size="sm"><Icon name="users" size={14} /> Proposer un jumelage</Button></div>
    </aside> : <div />}</div>
  </>;
}
window.Demandes = Demandes;
