// Generates supabase/functions/_shared/pdf/vendor/pdfmake.js: pdfmake's Node
// build and its dependencies (pdfkit, fontkit…) pre-bundled into one minified
// ES module, so the edge functions import it by relative path and no `npm:`
// pdfmake specifier reaches supabase/functions/deno.json or deno.lock.
//
// Why (ADR 0008, plan Task 3.30): the edge-runtime bundler embeds every npm
// package of the functions' lockfile in every function, so pdfmake in the
// shared lock made a supabase-js-only function 0.93 → 7.8 MB uploaded. A
// vendored file is part of a function only when its module graph imports it,
// i.e. only for the functions that render PDFs.
//
// The npm resolution is pinned by scripts/build-pdfmake.lock (--frozen): the
// same pdfkit 0.19.1 / fontkit 2.0.4 as the Task 3.29 measurements.
//
// Run: npm run build:pdfmake

const VERSION = '0.3.11'
const SPECIFIER = `npm:pdfmake@${VERSION}`
const LOCK = 'scripts/build-pdfmake.lock'
const OUT = 'supabase/functions/_shared/pdf/vendor/pdfmake.js'

/**
 * Node built-ins the bundle may `require()`. `deno bundle --minify` drops
 * Deno's `createRequire` injection, so the prelude supplies a closed
 * `require` that knows only these; the build fails if the bundle names any
 * other `node:` module outside a static import.
 */
const REQUIRABLE = [
  'node:buffer',
  'node:crypto',
  'node:events',
  'node:fs',
  'node:stream',
]

async function deno(args: string[]): Promise<string> {
  const { code, stdout, stderr } = await new Deno.Command('deno', {
    args,
    stdout: 'piped',
    stderr: 'piped',
  }).output()
  if (code !== 0) {
    throw new Error(
      `deno ${args[0]} failed:\n${new TextDecoder().decode(stderr)}`,
    )
  }
  return new TextDecoder().decode(stdout)
}

const pinned = ['--no-config', `--lock=${LOCK}`, '--frozen']
const bundle = await deno([
  'bundle',
  '--quiet',
  ...pinned,
  '--platform=deno',
  // tslib's `import` entry wraps its CommonJS build, which esbuild then fails
  // to interop (« Cannot destructure '__extends' »); `module` picks its ESM.
  '--conditions=module',
  '--minify',
  SPECIFIER,
])

// Every `node:` module named outside a static import must be requirable.
const named = new Set(
  [...bundle.matchAll(/(?<!from)"(node:[a-z_/]+)"/g)].map((m) => m[1]),
)
const unknown = [...named].filter((m) => !REQUIRABLE.includes(m))
if (unknown.length) {
  throw new Error(`the bundle requires unlisted built-ins: ${unknown}`)
}
if (bundle.split('export default ').length !== 2) {
  throw new Error('the bundle must have exactly one default export')
}

// License notices of every package in the resolved graph (some are
// tree-shaken away; listing them all errs on the safe side).
const info = JSON.parse(await deno(['info', '--json', ...pinned, SPECIFIER]))
const npmCache = JSON.parse(await deno(['info', '--json'])).npmCache as string
const packages = Object.values(
  info.npmPackages as Record<string, { name: string; version: string }>,
).sort((a, b) =>
  `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`)
)

const notices = await Promise.all(packages.map(async ({ name, version }) => {
  const dir = `${npmCache}/registry.npmjs.org/${name}/${version}`
  const pkg = JSON.parse(await Deno.readTextFile(`${dir}/package.json`))
  let text = ''
  for await (const entry of Deno.readDir(dir)) {
    if (entry.isFile && /^(licen[cs]e|copying)/i.test(entry.name)) {
      text = (await Deno.readTextFile(`${dir}/${entry.name}`)).trim()
      break
    }
  }
  const author = typeof pkg.author === 'string' ? pkg.author : pkg.author?.name
  const body = text ||
    `(no license file in the package; package.json: ${pkg.license}${
      author ? `, author ${author}` : ''
    })`
  return `${name}@${version} (${pkg.license ?? 'see below'})\n\n${body}`
}))

const comment = (text: string) =>
  text.replaceAll('*/', '* /').split('\n').map((l) => ` * ${l}`.trimEnd())
    .join('\n')

const header = `// @ts-self-types="./pdfmake.d.ts"
/*
 * GENERATED by scripts/build-pdfmake.ts from ${SPECIFIER} (Node build)
 * with \`deno bundle --minify\` (deno ${Deno.version.deno});
 * the npm resolution is pinned by ${LOCK}.
 * Do not edit; run \`npm run build:pdfmake\`.
 *
 * Imported only by supabase/functions/_shared/pdf/render.ts, so only the
 * functions that render PDFs carry it (CLAUDE.md §7).
 *
 * Prelude: module-scoped stand-ins for the Node globals the bundled CommonJS
 * code reads (\`Buffer\`, \`process\`, \`global\`, \`__dirname\`), and a closed
 * \`require\` that knows only:
 * ${REQUIRABLE.join(', ')}.
 * \`__dirname\` points nowhere: the renderer never uses pdfkit's standard fonts
 * or ICC profile, the only reads relative to it.
 *
 * Third-party notices:
 *
${comment(notices.join('\n\n----\n\n'))}
 */
`

const modules = REQUIRABLE.map((id, i) => ({ id, local: `__node${i}` }))
const local = (id: string) => modules.find((m) => m.id === id)!.local
const prelude = `${
  modules.map((m) => `import ${m.local} from '${m.id}'`).join('\n')
}
import process from 'node:process'
const { Buffer } = ${local('node:buffer')}
const global = globalThis
const __dirname = '/pdfmake-vendor'
const __builtins = {
${modules.map((m) => `  '${m.id}': ${m.local},`).join('\n')}
}
function require(id) {
  const m = __builtins[id]
  if (!m) throw new Error('pdfmake vendor: no require(' + id + ')')
  return m
}
`

await Deno.writeTextFile(OUT, header + prelude + bundle)
console.log(
  `Wrote ${OUT} (pdfmake ${VERSION}, ${
    (new TextEncoder().encode(header + prelude + bundle).length / 1e6).toFixed(
      2,
    )
  } MB, ${packages.length} packages)`,
)
