// Generates supabase/functions/_shared/pdf/fonts.ts: Inter 400 / 600 / 700
// (latin subset) from the @fontsource/inter devDependency, embedded as base64
// so edge functions need no file access (plan Task 3.29).
//
// WOFF 1, not WOFF2: fontkit 2.0.4 (through pdfkit) crashes while subsetting
// the composite glyphs of a WOFF2 font (é, à, ç…: « Offset is outside the
// bounds of the DataView »). WOFF 1 subsets correctly.
//
// Run: npm run build:pdf-fonts

const pkgDir = new URL('../node_modules/@fontsource/inter/', import.meta.url)
const outFile = new URL(
  '../supabase/functions/_shared/pdf/fonts.ts',
  import.meta.url,
)
const weights = [400, 600, 700] as const

const { version } = JSON.parse(
  await Deno.readTextFile(new URL('package.json', pkgDir)),
)

function toBase64(bytes: Uint8Array): string {
  let binary = ''
  for (let i = 0; i < bytes.length; i += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000))
  }
  return btoa(binary)
}

const entries = await Promise.all(weights.map(async (weight) => {
  const file = new URL(`files/inter-latin-${weight}-normal.woff`, pkgDir)
  return `  ${weight}:\n    '${toBase64(await Deno.readFile(file))}',`
}))

await Deno.writeTextFile(
  outFile,
  `// GENERATED by scripts/build-pdf-fonts.ts from @fontsource/inter ${version}
// (latin subset, WOFF). Do not edit; run \`npm run build:pdf-fonts\`.
// Inter: Copyright 2016 The Inter Project Authors (https://github.com/rsms/inter),
// SIL Open Font License 1.1.

/** Inter WOFF files by weight, base64-encoded. */
export const INTER_WOFF_BASE64 = {
${entries.join('\n')}
} as const
`,
)
console.log(`Wrote supabase/functions/_shared/pdf/fonts.ts (Inter ${version})`)
