// Generates supabase/functions/_shared/pdf/fonts.ts: Inter 400 / 600 / 700 in
// the latin, latin-ext and vietnamese subsets, from the @fontsource/inter
// devDependency, embedded as base64 so edge functions need no file access
// (plan Task 3.29), with each subset's code point ranges (the package's
// unicode.json). Also copies the package's LICENSE (SIL OFL 1.1) next to it as
// OFL-Inter.txt.
//
// pdfmake has no font fallback, so the renderer picks the subset per run of
// characters (render.ts). latin-ext covers names such as Łukasz, Ștefan,
// Dvořák, Ğül or Ÿ; vietnamese covers ễ, ạ, ư…
//
// WOFF 1, not WOFF2: fontkit 2.0.4 (through pdfkit) crashes while subsetting
// the composite glyphs of a WOFF2 font (é, à, ç…: « Offset is outside the
// bounds of the DataView »). WOFF 1 subsets correctly.
//
// Run: npm run build:pdf-fonts

const pkgDir = new URL('../node_modules/@fontsource/inter/', import.meta.url)
const outDir = new URL('../supabase/functions/_shared/pdf/', import.meta.url)
const weights = [400, 600, 700] as const
/** Lookup order: a character uses the first subset whose ranges hold it. */
const subsets = ['latin', 'latin-ext', 'vietnamese'] as const

const { version } = JSON.parse(
  await Deno.readTextFile(new URL('package.json', pkgDir)),
)
const unicode: Record<string, string> = JSON.parse(
  await Deno.readTextFile(new URL('unicode.json', pkgDir)),
)

function toBase64(bytes: Uint8Array): string {
  let binary = ''
  for (let i = 0; i < bytes.length; i += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000))
  }
  return btoa(binary)
}

const hex = (n: number) => `0x${n.toString(16).padStart(4, '0')}`

/** `U+0100-02BA,U+0304` → `[[0x0100, 0x02ba], [0x0304, 0x0304]]`. */
function ranges(subset: string): string {
  const spec = unicode[subset]
  if (!spec) throw new Error(`no unicode range for the ${subset} subset`)
  const pairs = spec.split(',').map((part) => {
    const m = /^U\+([0-9A-F]+)(?:-([0-9A-F]+))?$/i.exec(part.trim())
    if (!m) throw new Error(`bad unicode range « ${part} » (${subset})`)
    const from = parseInt(m[1], 16)
    return `[${hex(from)}, ${hex(m[2] ? parseInt(m[2], 16) : from)}]`
  })
  return `[\n    ${pairs.join(',\n    ')},\n  ]`
}

const files = await Promise.all(subsets.map(async (subset) => {
  const byWeight = await Promise.all(weights.map(async (weight) => {
    const file = new URL(
      `files/inter-${subset}-${weight}-normal.woff`,
      pkgDir,
    )
    return `    ${weight}:\n      '${toBase64(await Deno.readFile(file))}',`
  }))
  return `  '${subset}': {\n${byWeight.join('\n')}\n  },`
}))

await Deno.writeTextFile(
  new URL('fonts.ts', outDir),
  `// GENERATED by scripts/build-pdf-fonts.ts from @fontsource/inter ${version}
// (latin, latin-ext and vietnamese subsets, WOFF). Do not edit; run
// \`npm run build:pdf-fonts\`.
// Inter: Copyright 2016 The Inter Project Authors (https://github.com/rsms/inter),
// SIL Open Font License 1.1: the full text is in ./OFL-Inter.txt.

/** The embedded subsets, in lookup order (the first that holds a character wins). */
export const INTER_SUBSETS = [${
    subsets.map((s) => `'${s}'`).join(', ')
  }] as const

/** One embedded subset. */
export type InterSubset = (typeof INTER_SUBSETS)[number]

/** Inclusive code point ranges per subset (@fontsource/inter unicode.json). */
export const INTER_RANGES: Record<
  InterSubset,
  readonly (readonly [number, number])[]
> = {
${subsets.map((s) => `  '${s}': ${ranges(s)},`).join('\n')}
}

/** Inter WOFF files by subset and weight, base64-encoded. */
export const INTER_WOFF_BASE64: Record<
  InterSubset,
  Record<${weights.join(' | ')}, string>
> = {
${files.join('\n')}
}
`,
)

const license = await Deno.readTextFile(new URL('LICENSE', pkgDir))
if (!license.includes('SIL OPEN FONT LICENSE Version 1.1')) {
  throw new Error('@fontsource/inter LICENSE is not the OFL 1.1')
}
await Deno.writeTextFile(new URL('OFL-Inter.txt', outDir), license)

console.log(
  `Wrote supabase/functions/_shared/pdf/fonts.ts and OFL-Inter.txt (Inter ${version}, ${subsets.join(
    ', ',
  )})`,
)
