#!/usr/bin/env bash
# Clinique MANA Documenso — first-time setup, run ON THE DROPLET as root, from
# /opt/documenso-clinique (runbook: docs/runbooks/documenso-instance.md, step 3).
#
# Creates .env and cert.p12. Every secret is generated here and never leaves
# the server; the Resend key is typed at a silent prompt. Refuses to overwrite
# an existing .env or cert.p12 (rotating them is a separate, deliberate step).
set -euo pipefail
umask 077

DIR=/opt/documenso-clinique
DOMAIN=sign.cliniquemana.com
FROM_ADDRESS=signature@gestion.cliniquemana.com
FROM_NAME='Clinique MANA'
CONTAINER_UID=1001 # the image's `nodejs` user

cd "$DIR"
[[ -f compose.yml ]] || { echo "compose.yml missing in $DIR" >&2; exit 1; }
[[ -e .env ]] && { echo ".env already exists: not overwriting" >&2; exit 1; }
[[ -e cert.p12 ]] && { echo "cert.p12 already exists: not overwriting" >&2; exit 1; }

hex() { openssl rand -hex "$1"; }

read -r -s -p "Resend API key (sending access, gestion.cliniquemana.com): " RESEND_KEY
echo
[[ "$RESEND_KEY" == re_* ]] || { echo "That does not look like a Resend key (re_…)" >&2; exit 1; }

DB_PASSWORD=$(hex 24)
SIGNING_PASSPHRASE=$(hex 24)

# --- Signing certificate (seals signed PDFs). Self-signed, 10 years, like PS Hub's.
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
  -subj "/C=CA/ST=Quebec/L=Montreal/O=Clinique MANA/CN=$DOMAIN" \
  -keyout "$TMP/key.pem" -out "$TMP/cert.pem" 2>/dev/null
openssl pkcs12 -export -name "Clinique MANA" \
  -inkey "$TMP/key.pem" -in "$TMP/cert.pem" \
  -out cert.p12 -passout "pass:$SIGNING_PASSPHRASE"
chown "$CONTAINER_UID" cert.p12
chmod 0400 cert.p12

# --- .env (root only). Values are hex or fixed text: no quoting needed except FROM_NAME.
cat > .env <<EOF
# Clinique MANA Documenso — generated by setup.sh on $(date -u +%FT%TZ). Root only (0600).
POSTGRES_USER=documenso
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=documenso
NEXT_PRIVATE_DATABASE_URL=postgresql://documenso:$DB_PASSWORD@database:5432/documenso

NEXTAUTH_SECRET=$(hex 32)
NEXT_PRIVATE_ENCRYPTION_KEY=$(hex 32)
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=$(hex 32)
NEXT_PUBLIC_WEBAPP_URL=https://$DOMAIN

NEXT_PRIVATE_RESEND_API_KEY=$RESEND_KEY
NEXT_PRIVATE_SMTP_FROM_NAME="$FROM_NAME"
NEXT_PRIVATE_SMTP_FROM_ADDRESS=$FROM_ADDRESS

NEXT_PRIVATE_SIGNING_PASSPHRASE=$SIGNING_PASSPHRASE
NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=20

# true once the admin account exists (runbook step 5)
NEXT_PUBLIC_DISABLE_SIGNUP=false
EOF
chmod 0600 .env
unset RESEND_KEY DB_PASSWORD SIGNING_PASSPHRASE

docker compose config --quiet
echo "OK: .env and cert.p12 created. Next: docker compose up -d (runbook step 4)."
