export { ProfessionalProfileTab } from './profile-tab'
export { ProfessionalPortraitTab } from './portrait-tab'
export { ProfessionalDocumentsTab } from './documents-tab'
export { ProfessionalFicheTab } from './fiche-tab'
export { ProfessionalHistoryTab } from './history-tab'
